on:
  #pull_request:
  push:
    #branches:
      #-main 
      #-master
    #types: [closed]

      

name: Create Release

jobs:
  release:
    runs-on: ubuntu-latest
    #if: github.event.pull_request.merged == true
    steps:
      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Tag name
          release_name: Release 
          draft: true
          prerelease: false

      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
